// src/faq.js: curated answers (English + Kiswahili) from the website content. Edit here; no other code needs to change.
// Keywords are lowercase, no punctuation, comma separated; a phrase scores higher than a single word.
export const C={email:'ligospace.ke@gmail.com',phone:'0182809790',base:'Kajiado South, Kenya'};
export const PAGES={'/about':['About us','Kuhusu sisi'],'/work':['Our Work','Kazi yetu'],'/future':['Future Initiatives','Mipango ya baadaye'],'/engage/involve':['Get Involved','Jiunge nasi'],'/engage/partner':['Partner with us','Shirikiana nasi'],'/opportunities':['Opportunities','Fursa'],'/events':['Events','Matukio'],'/contact':['Contact','Wasiliana nasi'],'/founder':['Meet the founder','Mwanzilishi'],'/shs':['Synchronized Human System','Synchronized Human System'],'/impact':['Impact','Athari'],'/team':['Team','Timu'],'/account':['Sign in','Ingia']};
export const FAQ=[
{id:'sacco',k:'sacco,saccos,deposit,deposits,savings,save money,loan,loans,akiba,mkopo,amana,kuweka pesa',go:'/future',
 en:`The L.I.G.O. SACCO is a future initiative and is not operational. It is subject to the required registration and authorization (SASRA). No deposits, savings or loans are offered or accepted.`,
 sw:`L.I.G.O. SACCO ni mpango wa baadaye na haujaanza kufanya kazi. Unasubiri usajili na idhini zinazohitajika (SASRA). Hakuna amana, akiba wala mikopo inayotolewa au kupokelewa.`},
{id:'university',k:'university,universities,admission,admissions,academy,chuo kikuu,shahada,udahili,kujiunga na chuo',go:'/future',
 en:`L.I.G.O. University is a long-term vision only, not an existing university, and L.I.G.O. Academy is a possible future institution. Both would need to meet Kenyan legal, academic and accreditation requirements (CUE) before offering any qualification. We do not offer degrees or admissions today.`,
 sw:`L.I.G.O. University ni maono ya muda mrefu tu, si chuo kikuu kilichopo, na L.I.G.O. Academy ni taasisi inayoweza kuanzishwa baadaye. Zote zitahitaji kutimiza masharti ya kisheria, kitaaluma na uthibitisho wa Kenya (CUE) kabla ya kutoa sifa yoyote. Hatutoi shahada wala udahili kwa sasa.`},
{id:'training',k:'vocational,tvet,tveta,training center,training centre,courses,course,certificate,kozi,mafunzo,ufundi,cheti,chuo cha ufundi',go:'/opportunities',
 en:`The L.I.G.O. Skills & Vocational Training Center is a future initiative, subject to TVET registration and licensing, so we are not offering accredited courses yet. Today you can join our mentorship, talent and life-skills programs and watch the Opportunities page for training from partners.`,
 sw:`Kituo cha L.I.G.O. cha Ujuzi na Mafunzo ya Ufundi ni mpango wa baadaye, unaosubiri usajili na leseni za TVET, kwa hivyo hatutoi kozi zilizoidhinishwa bado. Kwa sasa unaweza kujiunga na programu zetu za ushauri, vipaji na stadi za maisha, na kufuatilia ukurasa wa Fursa kwa mafunzo kutoka kwa washirika.`},
{id:'donate',k:'donate,donation,donations,give money,contribute money,mchango,changia,kuchangia,toa pesa,mpesa,m pesa',go:'/engage/partner',
 en:`Online donations and payments are not open yet. They will start only once our legal and financial arrangements are in place. To show your interest in supporting approved initiatives, use Partner with us and choose Sponsor / Donor.`,
 sw:`Michango na malipo ya mtandaoni bado hayajafunguliwa. Yataanza tu baada ya mipango yetu ya kisheria na kifedha kukamilika. Ili kuonyesha nia ya kusaidia miradi iliyoidhinishwa, tumia Shirikiana nasi na uchague Mdhamini / Mfadhili.`},
{id:'join',k:'join,get involved,volunteer,become a member,how can i help,kujiunga,kujitolea,jinsi ya kujiunga,mwanachama,kushiriki,nataka kusaidia',go:'/engage/involve',
 en:`There is a place for you. On the Get Involved page choose your pathway (volunteer, youth participant, founding member, mentor, skills contributor, opportunity connection or community participant) and fill the short form. Our team reviews it and contacts you with the next step.`,
 sw:`Kuna nafasi kwa ajili yako. Kwenye ukurasa wa Jiunge nasi chagua njia yako (kujitolea, kijana mshiriki, mwanachama mwanzilishi, mshauri, mchangiaji wa ujuzi, uunganishaji wa fursa au mshiriki wa jamii) kisha jaza fomu fupi. Timu yetu itaipitia na kukuarifu hatua inayofuata.`},
{id:'partner',k:'partner,partnership,partner with us,sponsor,collaborate,collaboration,ushirikiano,kushirikiana,mdhamini,udhamini,shirikiana',go:'/engage/partner',
 en:`We cannot build alone. Choose your pathway on Partner with us: academic, corporate, sponsor or donor, international, community, technology, school or expert partner. Each has a short form and our team follows up.`,
 sw:`Hatuwezi kujenga peke yetu. Chagua njia yako kwenye Shirikiana nasi: mshirika wa kitaaluma, wa kampuni au taasisi, mdhamini au mfadhili, wa kimataifa, wa jamii, wa teknolojia, wa shule au mtaalamu. Kila njia ina fomu fupi na timu yetu itafuatilia.`},
{id:'wellness',k:'wellness,wellbeing,women,womens,men,mens,mentorship,mentor,mentoring,afya,ustawi,wanawake,wanaume,ushauri,mshauri',go:'/team',
 en:`We have Women's Wellness Mentorship and Men's Wellness Mentorship programs, offered by members who are independent mentors, and youth mentorship is part of our work too. This is peer and life-skills support, not medical treatment or therapy.`,
 sw:`Tuna programu za Ushauri wa Afya na Ustawi kwa Wanawake na kwa Wanaume, zinazotolewa na wanachama walio washauri huru, na ushauri kwa vijana pia ni sehemu ya kazi yetu. Huu ni msaada wa wenzao na stadi za maisha, si matibabu wala tiba ya kisaikolojia.`},
{id:'children',k:'child,children,kids,vulnerable,safeguarding,child protection,watoto,mtoto,wanyonge,ulinzi wa mtoto',go:'/work',
 en:`Our work with children and vulnerable communities is dignity-centered. Members offering these programs are not contacted directly: introductions are arranged through L.I.G.O. SPACE. Our safeguarding and child-protection policies are being developed. If a child is in danger, call Childline Kenya on 116 or 999.`,
 sw:`Kazi yetu na watoto na jamii zilizo hatarini inajali utu. Wanachama wanaotoa programu hizi hawawasiliani moja kwa moja: utambulisho hupangwa kupitia L.I.G.O. SPACE. Sera zetu za ulinzi na ulinzi wa mtoto zinaandaliwa. Ikiwa mtoto yuko hatarini, piga Childline Kenya 116 au 999.`},
{id:'account',k:'sign in,login,log in,password,account,dashboard,profile,register,sign up,ingia,nenosiri,akaunti,jisajili,wasifu',go:'/account',
 en:`Accounts are created by the L.I.G.O. SPACE team after your application is approved. You receive a temporary password to sign in and then choose your own. Forgot your password? Contact the team and we will reset it. To apply, use Get Involved.`,
 sw:`Akaunti huundwa na timu ya L.I.G.O. SPACE baada ya ombi lako kuidhinishwa. Unapewa nenosiri la muda la kuingia kisha unachagua lako mwenyewe. Umesahau nenosiri? Wasiliana na timu nasi tutakuwekea jipya. Ili kuomba, tumia Jiunge nasi.`},
{id:'opportunities',k:'job,jobs,employment,scholarship,scholarships,internship,internships,opportunity,opportunities,fellowship,ajira,udhamini wa masomo,fursa,nafasi,mafunzo kazini',go:'/opportunities',
 en:`The L.I.G.O. Opportunity Circle is being developed to connect people with jobs, internships, scholarships, training, mentorship and more. Opportunities will appear on the Opportunities page once verified. If you have one to share, use Get Involved and choose Opportunity / Employment Connection.`,
 sw:`L.I.G.O. Opportunity Circle inaendelezwa ili kuunganisha watu na ajira, mafunzo kazini, udhamini wa masomo, mafunzo, ushauri na zaidi. Fursa zitaonekana kwenye ukurasa wa Fursa zikishathibitishwa. Ukiwa na fursa ya kushiriki, tumia Jiunge nasi na uchague Uunganishaji wa Fursa / Ajira.`},
{id:'app',k:'app,application,mobile app,play store,digital library,library,programu ya simu,maktaba',go:'/future',
 en:`The Digital Library and AI Learning Assistant are in development, and the L.I.G.O. App is a longer-term initiative. None of them is available yet. See Future Initiatives for the status of everything.`,
 sw:`Maktaba ya Kidijitali na Msaidizi wa Kujifunza wa AI zinaendelezwa, na Programu ya L.I.G.O. ni mpango wa muda mrefu zaidi. Hakuna kati ya hivyo kinachopatikana bado. Tazama Mipango ya baadaye kwa hali ya kila kitu.`},
{id:'launch',k:'launch,launching,5 december,december 5,event,events,when is the launch,uzinduzi,tarehe ya uzinduzi,tukio,matukio',go:'/events',
 en:`The official L.I.G.O. SPACE launch is on 5 December 2026. Event details and registration will be published on the Events page.`,
 sw:`Uzinduzi rasmi wa L.I.G.O. SPACE ni tarehe 5 Desemba 2026. Maelezo ya tukio na usajili yatachapishwa kwenye ukurasa wa Matukio.`},
{id:'contact',k:'contact,phone,phone number,email,e mail,call you,reach you,address,contact us,wasiliana,nambari,namba ya simu,simu,barua pepe,mawasiliano,kuwasiliana',go:'/contact',
 en:`You can reach L.I.G.O. SPACE on ${C.phone} or ${C.email}. We are based in ${C.base}.`,
 sw:`Unaweza kuwasiliana na L.I.G.O. SPACE kupitia ${C.phone} au ${C.email}. Tuko ${C.base}.`},
{id:'location',k:'where are you,location,located,based,office,visit you,kajiado,mko wapi,mahali,ofisi,mnapatikana wapi',go:'/about',
 en:`We are rooted in Kajiado South, Kenya, and our vision reaches from Kajiado South to Kenya, Africa and the wider world.`,
 sw:`Mizizi yetu iko Kajiado Kusini, Kenya, na maono yetu yanaanzia Kajiado Kusini hadi Kenya, Afrika na ulimwengu mzima.`},
{id:'founder',k:'founder,who founded,samuel,president,leader,leadership,founded,mwanzilishi,mwenyekiti,kiongozi,aliyeanzisha',go:'/founder',
 en:`L.I.G.O. SPACE was founded by Samuel M.K., Founder & President. You can read his message and story on the Founder page, and meet our team on the Team page.`,
 sw:`L.I.G.O. SPACE ilianzishwa na Samuel M.K., Mwanzilishi na Rais. Unaweza kusoma ujumbe na hadithi yake kwenye ukurasa wa Mwanzilishi, na kukutana na timu yetu kwenye ukurasa wa Timu.`},
{id:'shs',k:'synchronized,synchronised,shs,human system,body mind,mfumo',go:'/shs',
 en:`The Synchronized Human System is a developing framework from L.I.G.O. SPACE's work. It looks at six connected dimensions: body, mind, emotion, identity, relational and purpose. It is open to academic examination and critique and is not presented as established science.`,
 sw:`Synchronized Human System ni mfumo unaokua kutokana na kazi ya L.I.G.O. SPACE. Unaangalia nyanja sita zinazohusiana: mwili, akili, hisia, utambulisho, mahusiano na kusudi. Uko wazi kwa uchunguzi na ukosoaji wa kitaaluma na hauwasilishwi kama sayansi iliyothibitishwa.`},
{id:'impact',k:'impact,how many people,numbers,statistics,results,reach,athari,takwimu,matokeo,watu wangapi',go:'/impact',
 en:`Our impact dashboard separates Target, Achieved and Verified, and we never invent numbers. Figures are targets until activities are documented and verified. See the Impact page for the current baseline.`,
 sw:`Dashibodi yetu ya athari inatenganisha Lengo, Lililofikiwa na Lililothibitishwa, na hatubuni namba kamwe. Namba ni malengo hadi shughuli zitakapoandikwa na kuthibitishwa. Tazama ukurasa wa Athari kwa hali ya sasa.`},
{id:'vision',k:'vision,mission,values,maono,dhamira,maadili',go:'/about',
 en:`Our vision is a world where every person can live with dignity, discover their potential, develop their capabilities and contribute meaningfully to society. Our mission is to restore opportunity, dignity and purposeful pathways by connecting people with knowledge, relationships, resources, technology, education and practical opportunities.`,
 sw:`Maono yetu ni ulimwengu ambamo kila mtu anaweza kuishi kwa utu, kugundua uwezo wake, kuukuza na kuchangia jamii kwa maana. Dhamira yetu ni kurejesha fursa, utu na njia zenye kusudi kwa kuunganisha watu na maarifa, mahusiano, rasilimali, teknolojia, elimu na fursa za vitendo.`},
{id:'work',k:'what do you do,programs,programmes,services,what you offer,mnafanya nini,mnatoa huduma gani,programu,huduma zenu,kazi zenu',go:'/work',
 en:`Our programs cover youth and young people, children and vulnerable communities, education and human development, talent and creativity, families and relationships, livelihoods and employment, and women's and men's wellness mentorship. Members offer these programs; L.I.G.O. SPACE connects you with them.`,
 sw:`Programu zetu zinahusu vijana, watoto na jamii zilizo hatarini, elimu na maendeleo ya binadamu, vipaji na ubunifu, familia na mahusiano, kipato na ajira, pamoja na ushauri wa afya na ustawi kwa wanawake na wanaume. Wanachama hutoa programu hizi; L.I.G.O. SPACE inakuunganisha nao.`},
{id:'about',k:'what is ligo,who are you,about ligo,about you,who we are,ligo space ni nini,nyinyi ni nani,kuhusu ligo,kuhusu nyinyi,shirika lenu',go:'/about',
 en:`L.I.G.O. SPACE is a human-centered institution rooted in Kajiado South, Kenya. We build pathways of dignity, opportunity, connection and purposeful living, connecting people with education, skills, technology, enterprise and each other. Humanity First. Every Life Matters.`,
 sw:`L.I.G.O. SPACE ni taasisi inayomweka mwanadamu kwanza, yenye mizizi Kajiado Kusini, Kenya. Tunajenga njia za utu, fursa, uhusiano na maisha yenye kusudi, tukiunganisha watu na elimu, ujuzi, teknolojia, biashara na jamii. Utu Kwanza. Kila Maisha Yana Thamani.`},
{id:'fees',k:'cost,fee,fees,price,how much,free,pay,bei,gharama,bure,kiasi gani,malipo',go:'/contact',
 en:`I don't have published fees or prices. Programs are offered by members and partners, so details vary. Please contact the team on ${C.phone} or ${C.email} for specifics.`,
 sw:`Sina ada wala bei zilizochapishwa. Programu zinatolewa na wanachama na washirika, kwa hivyo maelezo hutofautiana. Tafadhali wasiliana na timu kupitia ${C.phone} au ${C.email} kwa maelezo zaidi.`},
{id:'privacy',k:'privacy,data,personal information,my information,safe,faragha,taarifa binafsi,data yangu',go:'/contact',
 en:`Please don't share sensitive personal details in this chat. Members choose whether their profile is public, and hidden profiles are never shown. We are preparing our privacy and data-protection policies.`,
 sw:`Tafadhali usishiriki taarifa nyeti binafsi kwenye mazungumzo haya. Wanachama huchagua kama wasifu wao uonekane hadharani, na wasifu uliofichwa haupatikani kamwe. Tunaandaa sera zetu za faragha na ulinzi wa data.`},
{id:'language',k:'swahili,kiswahili,english,lugha,language',go:null,
 en:`I can answer in English and Kiswahili. Other languages will come later. Use the EN / SW buttons above or just write in your language.`,
 sw:`Naweza kujibu kwa Kiingereza na Kiswahili. Lugha nyingine zitaongezwa baadaye. Tumia vitufe vya EN / SW hapo juu au andika tu kwa lugha yako.`},
{id:'thanks',k:'thanks,thank you,asante,asante sana,shukrani',go:null,en:`You're welcome! Is there anything else I can help with?`,sw:`Karibu! Kuna jambo lingine ninaloweza kukusaidia?`},
{id:'greeting',k:'hello,hi,hey,good morning,good afternoon,hujambo,habari,mambo,salaam,shikamoo,vipi,niaje',go:null,
 en:`Hello! I can answer questions about L.I.G.O. SPACE, our programs, how to join or partner, and our launch on 5 December 2026. What would you like to know?`,
 sw:`Habari! Naweza kujibu maswali kuhusu L.I.G.O. SPACE, programu zetu, jinsi ya kujiunga au kushirikiana nasi, na uzinduzi wetu tarehe 5 Desemba 2026. Ungependa kujua nini?`}
];
export const SAFE={
 en:`I'm really sorry you are going through this, and I'm glad you reached out. I'm an automated assistant and cannot give crisis support, but you deserve help right now. If you or someone else is in immediate danger, call 999 or 112. Kenya Red Cross (free, 24/7): 1199. For a child in danger or who needs to talk: Childline Kenya, 116. For gender-based violence: 1195. Please also tell someone you trust who is near you. L.I.G.O. SPACE is not an emergency service.`,
 sw:`Pole sana kwa unayopitia, na nashukuru umeomba msaada. Mimi ni msaidizi wa kiotomatiki na siwezi kutoa msaada wa dharura, lakini unastahili msaada sasa hivi. Ikiwa wewe au mtu mwingine yuko hatarini mara moja, piga 999 au 112. Msalaba Mwekundu Kenya (bure, saa 24): 1199. Mtoto aliye hatarini au anayehitaji kuzungumza: Childline Kenya, 116. Kwa ukatili wa kijinsia: 1195. Tafadhali mwambie pia mtu unayemwamini aliye karibu nawe. L.I.G.O. SPACE si huduma ya dharura.`};
export const FALL={
 en:`I don't have an answer for that yet. Please contact the L.I.G.O. SPACE team on ${C.phone} or ${C.email}, or browse the pages of this site.`,
 sw:`Sina jibu la swali hilo bado. Tafadhali wasiliana na timu ya L.I.G.O. SPACE kupitia ${C.phone} au ${C.email}, au tembelea kurasa za tovuti hii.`};
